- name: variables from promt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: true

  - name: PASSWORD
    prompt: pelase enter your password
    private: true
  tasks:
  - name: printing user information
    ansible.builtin.debug:
      msg: "Hello Username is: {{ USERNAME }}, password is : {{ PASSWORD }}"