- name: understand vars preference
  hosts: local
  connection: local
  # vars:
  #   GREETING: "Hello from PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: please enter the greeting
  #   private: false
  tasks:
  - name: print the greeting
    # vars:
    #   GREETING: "Hello from TASK"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"



#1. commad line or args
#2.Task
#3.file
#4.prompt
#5.PLAY
#6.Inventory
