- name: install packages
  hosts: frontend
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mariadb105-server
        - nginx
        - zip
