- name: user creation #imagine no user module
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exit or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true


  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0 #it means above task failure

  - name: user already exists
    ansible.builtin.debug:
      msg: "user already exists"
    when: output.rc == 0 #it means above task failure


# #ansible error handling
# ======================
# Error handling means what should we do when error comes, what should we do when error not comes.

# if we are able to handle the error, we can keep ignore_errors true and then execute another task in case of failure
