- name: install nginx
  hosts: dynamic_frontend
  become: yes
  serial: 5 #excutes playbook for every 5 servers
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes